/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipientRouteImport } from './routes/recipient'
import { Route as PairRouteImport } from './routes/pair'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuardianDashboardRouteImport } from './routes/guardian.dashboard'

const RecipientRoute = RecipientRouteImport.update({
  id: '/recipient',
  path: '/recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianDashboardRoute = GuardianDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GuardianRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRouteWithChildren
  '/pair': typeof PairRoute
  '/recipient': typeof RecipientRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRouteWithChildren
  '/pair': typeof PairRoute
  '/recipient': typeof RecipientRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRouteWithChildren
  '/pair': typeof PairRoute
  '/recipient': typeof RecipientRoute
  '/guardian/dashboard': typeof GuardianDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guardian' | '/pair' | '/recipient' | '/guardian/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guardian' | '/pair' | '/recipient' | '/guardian/dashboard'
  id:
    | '__root__'
    | '/'
    | '/guardian'
    | '/pair'
    | '/recipient'
    | '/guardian/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuardianRoute: typeof GuardianRouteWithChildren
  PairRoute: typeof PairRoute
  RecipientRoute: typeof RecipientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipient': {
      id: '/recipient'
      path: '/recipient'
      fullPath: '/recipient'
      preLoaderRoute: typeof RecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/dashboard': {
      id: '/guardian/dashboard'
      path: '/dashboard'
      fullPath: '/guardian/dashboard'
      preLoaderRoute: typeof GuardianDashboardRouteImport
      parentRoute: typeof GuardianRoute
    }
  }
}

interface GuardianRouteChildren {
  GuardianDashboardRoute: typeof GuardianDashboardRoute
}

const GuardianRouteChildren: GuardianRouteChildren = {
  GuardianDashboardRoute: GuardianDashboardRoute,
}

const GuardianRouteWithChildren = GuardianRoute._addFileChildren(
  GuardianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuardianRoute: GuardianRouteWithChildren,
  PairRoute: PairRoute,
  RecipientRoute: RecipientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
